config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users
    resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events
    resources :problems
    resources :notes, only: [:index, :show]
    resources :coggins, only: [:index, :show]
    resources :issues, only: [:show]
    resources :medications, only: [:index, :show]
    resources :plans do
      resources :subscriptions
    end
    mount StripeEvent::Engine, at: '/stripe_events'
  end

  resources :horses do
    resources :users, only: [:show]
    resources :events
    resources :problems, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
    resources :coggins, except: [:index, :show]
    resources :issues
    resources :medications

  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :events
  resources :problems
  resources :coggins
  resources :issues
  resources :medications
  resources :charges


  get '/horses/:user_id', to: 'problems#problems'
  root 'users#new'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

end







# Define abilities for the passed in user here. For example:
    #

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def admin?
    role == "admin"
  end

  def manager?
    role == "manager"
  end

  def employee?
    role == "employee"
  end

  def boarder?
    role == "boarder"
  end 
  
end

app/models/charge.rb
class Charge < ApplicationRecord
    has_and_belongs_to_many :horses
    belongs_to :user
end

app/models/coggin.rb
class Coggin < ApplicationRecord
  belongs_to :horse
  
  mount_uploader :coggin, CogginUploader # Tells rails to use this uploader for this model.
  validates :coggin, presence: true

  end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/farrier.rb
class Farrier < ApplicationRecord
  has_many :horses

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true
  
end

app/models/horse.rb
class Horse < ApplicationRecord

  belongs_to :user
  belongs_to :veterinarian
  belongs_to :farrier
  has_many :problems
  has_many :medications
  has_many :notes
  has_many :coggins

  mount_uploader :picture, PictureUploader

  validates :barn_name, presence: true
  validates :breed, presence: true
  validates :user_id, presence: true
  validates :veterinarian_id, presence: true
  validates :farrier_id, presence: true
end

app/models/medication.rb
class Medication < ApplicationRecord
    belongs_to :horse
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :horse
  
  validates :text,
  presence: true,
  length: { minimum: 10, maximum: 2000 }

end

app/models/problem.rb
class Problem < ApplicationRecord

    belongs_to :horse

    validates :horse, presence: true
    validates :date, presence: true
    validates :description, presence: true
    validates :time, presence: true









  end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :confirmable

  has_many :horses
  has_many :charges
  has_many :problems
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true

end

app/models/veterinarian.rb
class Veterinarian < ApplicationRecord
  has_many :horses

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authorize_user, except: [:show]
  after_action :verify_authorized


  def show
    @note = Note.find(params[:id])
    @horse = @note.horse
    authorize @note
  end

  def new
    @note = Note.new
    authorize @note

  end

  def create
    @note = Note.new(note_params)
    authorize @note
    if @note.save
      flash[:notice] = "New Note Added!"
      redirect_to @note
    else
      flash[:alert] = "New Note Not Created"
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
    authorize @note
  end

  def update
   @note = Note.find(params[:id])
   authorize @note
   if @note.update_attributes(note_params)
     flash[:notice] = "Note Updated!"
     redirect_to @note
   else
     render :edit
   end
 end

  def destroy
    @note = Note.find(params[:id])
    authorize @note
    if @note.destroy
      flash[:notice] = 'Note has been deleted.'
      redirect_to new_note_path
    end
  end

  private

  def note_params
    params.require(:note).permit(
      :text,
      :horse_id
    )
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authorize_user, except: [:new]

  def show
    @user = User.find(params[:id])
    authorize @user
    @horse = Horse.all
    @chafges = Charge.all
    @events = Event.all
    @problems = Problem.all
    @notes = Note.all
    @problem = Problem.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account was successfully created'
      redirect_to current_user_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'User has been deleted.'
      redirect_to new_user_path
    end
  end

def user_params
  params.require(:user).permit(
      :name,
      :phone_number,
      :address,
      :city,
      :state,
      :zip_code,
      :email,
      :password
  )
  end

  def authorize_user
    if !user_signed_in?
      redirect_to root_url
      flash[:alert] = "ERROR: You need to sign in or sign up before continuing!"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coggins_helper.rb
module CogginsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/veterinarians_helper.rb
module VeterinariansHelper

end

app/views/notes/edit.html.erb
<br></br>
<%= simple_form_for @note do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation-note">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <%= f.label :horse_id, 'Horse', class: 'form-actions' %>
      <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
      <%= f.label :text, 'Enter Note', class: 'form-actions' %>
      <%= f.text_area :text %>
      <div class="form-actions">
        <%= f.button :submit, 'Update' %>
        <p><%= link_to "Delete Note", note_path(@note.id), data: { confirm: "Are you sure?" }, method: :delete %> <br />
          <%= link_to "Back", :back, class: 'link' %></p>
    <% end %>

<div class='container'>
  <%= bootstrap_form_for(@note) do |f| %>
    <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
    <%= f.text_area :text %>
    <%= f.submit "Update", class: 'btn btn-success' %> <%= link_to "Back", user_path(@current_user), class:'btn btn-outline-secondary' %>
    <br />
    <br />
    <%= link_to "Delete Note", note_path(@note.id), data: { confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger' %>
  <% end %>
</div>

app/views/notes/index.html.erb
<h1 class="text-center">Canvas</h1>

<canvas id="c" width="500" height="500" style="border:1px solid #ccc"></canvas>

app/views/notes/new.html.erb
<br></br>
<%= simple_form_for @note do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation-note">
        <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  
  <div class='container'>
  <%= bootstrap_form_for(@note) do |f| %>
    <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
    <%= f.text_area :text %>
    <%= f.submit "Submit", class: 'btn btn-success' %> <%= link_to "Back", :back, class:'btn btn-outline-secondary' %>
    <br />
    <br />
    <%= link_to "Home", user_path(@current_user), class: 'btn btn-sm btn-primary' %>
  <% end %>
</div>

app/views/notes/show.html.erb
<br />
<div class='container'>
<div class="row">
  <div class="small-6 large-centered columns">
    <div class='note_info'>
      <h1 class='note_data'><%= @note.created_at.strftime("%b. %d, %Y") %></h1>
      <h2 class='note_header'><%= @note.horse.barn_name  %><h2>
      <h3 class='note_data'><%= @note.text %></h3>
      <% if current_user.admin? || current_user.manager? %>
        <%= link_to 'Edit', edit_note_path(params[:id]) %> <br />
        <%= link_to 'Back to Horse', horse_path(@note.horse_id) %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<br />
<div class='container'>
  <div class='row justify-content-md-center'>
    <% if user_signed_in? %>
    <% else %>
      <div class='large-6 large-centered columns'>
        <%= link_to 'Sign In', new_user_session_path, class:"btn btn-lg btn-primary" %>
        <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-lg btn-info" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col">
          <h5 class='display-4 text-center'>Your Information<h5>
        <div class='container text-center'>
          <h1><%= @user.name %></h1>
          <%= @user.phone_number %><br />
          <%= @user.address %> <br />
          <%= @user.city %>, <%= @user.state %> <%= @user.zip_code %></p>
          <p><%= @user.email %><br />
        </div>
    </div>
  </div>
</div>
<!-------- Admin Add/View Roles-------->
<div class="container text-center">
  <div class="row">
    <div class="col-sm">
      <% if current_user.admin? %>
              <h3 class='text-center' id="allHorses">All Horses</h3>
              <% @horse.each do |h| %>
              <a class="list-group-item list-group-item-action text-center overflow-auto" href=<%= horse_path(h.id) %>><%= h.barn_name %></a>
        <% end %>
  </div>
    <div class="col-md">
      <h3 class='text-center' id="allAdmin">Admin Functions</h3>
        <div class="list-group text-center" id="adminViews">
          <a href= <%= new_horse_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Horse</a>
          <a href= <%= new_coggin_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Coggins File</a>
          <a href= <%= new_charge_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Charge</a>
          <a href= <%= new_note_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Note</a>
          <a href= <%= new_veterinarian_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Veterinarian</a>
          <a href= <%= new_farrier_path %> class="list-group-item list-group-mine list-group-item-action text-primary">Add New Farrier</a>
          <a href= <%= veterinarians_path %> class="list-group-item list-group-mine list-group-item-action text-info">View Active Veterinarians</a>
          <a href= <%= farriers_path %> class="list-group-item list-group-mine list-group-item-action text-info">View Active Farriers</a>
        </div>
    </div>
<!--------Non Admin View Below--------->
  <% else %>
  <div class="row justify-content-sm-center">
    <div class="col-sm-6 ">
      <div class="card">
        <div class="card-header text-center">
         Your Horses
        </div>
        <div class="list-group list-group-flush">
        <% @horse.each do |h| %>
        <% if h.user.id === @user.id %>
          <ul class="list-group list-group-horizontal">
            <a class="list-group-item list-group-item-action" href=<%= horse_path(h.id) %>><%= h.barn_name%></a>
          </ul>
            <% end %>
          <% end %>
        <% end %>
        </div>
      </div>
  </div>
  <br />
<!------------ Modals ----------->

  <!-- Modal Add Problem -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
  <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add A New problem</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
          <div class="modal-body">
            <%= render template: "/problems/_new" %>
          </div>
    </div>
    </div>
  </div>
</div>

<!-- Modal Edit Users -->
  <div class="modal fade" id="editUsers" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
        <h4 class="modal-title">Edit Users</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
         <div class="modal-body">
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<br />
<br />
<!-- Calendar 
<div class="container">
  <% if current_user.admin? || current_user.manager?  %>
    <div class='calendar'></div>
    <% else %>
    <div class='usr_calendar'></div>
  <% end %>
</div> -->