config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users
    resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events
    resources :problems
    resources :notes, only: [:index, :show]
    resources :coggins, only: [:index, :show]
    resources :issues, only: [:show]
    resources :medications, only: [:index, :show]
    resources :plans do
      resources :subscriptions
    end
    mount StripeEvent::Engine, at: '/stripe_events'
  end

  resources :horses do
    resources :users, only: [:show]
    resources :events
    resources :problems, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
    resources :coggins, except: [:index, :show]
    resources :issues
    resources :medications

  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :events
  resources :problems
  resources :coggins
  resources :issues
  resources :medications
  resources :charges


  get '/horses/:user_id', to: 'problems#problems'
  root 'users#new'
end

app/models/coggin.rb
class Coggin < ApplicationRecord
  belongs_to :horse
  
  mount_uploader :coggin, CogginUploader # Tells rails to use this uploader for this model.
  validates :coggin, presence: true

  end

app/controllers/coggins_controller.rb
class CogginsController < ApplicationController
  before_action :authorize_user
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  
  def index
    @coggins = policy_scope(Coggin).all
    #@horse  = Horse.find()
    end

  def show
    @coggin = Coggin.find(params[:id])
    @horse = @coggin.horse
    authorize @coggin
  end

  def new
    @coggin = Coggin.new
    authorize @coggin
  end

  def create
    @coggin = Coggin.new(coggin_params)
    authorize @coggin
    if @coggin.save
      flash[:notice] = "New Coggins File Added!"
      redirect_to coggins_path
    else
      flash[:alert] = "New Coggin Not Created"
      render :new
    end
  end

  def edit
    @coggin = Coggin.find(params[:id])
    authorize @coggin
  end

  def update
   @coggin = Coggin.find(params[:id])
   authorize @coggin
   if @coggin.update_attributes(coggin_params)
     flash[:notice] = "Coggin Updated!"
     redirect_to @coggin
   else
     render 'edit'
   end
 end

  def destroy
    @coggin = policy_scope(Coggin).find(params[:id])
    authorize @coggin
    if @coggin.destroy
      flash[:notice] = 'Coggin has been deleted.'
      redirect_to coggins_path
    end
  end

  private

  def coggin_params
    params.require(:coggin).permit(
      :horse_id,
      :coggin
    )
  end

  def authorize_user
    if !user_signed_in?
      redirect_to root_url
      flash[:alert] = "Access Denied: You need to sign in or sign up before continuing!"
    end
  end
  
end

app/helpers/coggins_helper.rb
module CogginsHelper
end

app/views/coggins/destroy.html.erb
<h1>Coggins#destroy</h1>
<p>Find me in app/views/coggins/destroy.html.erb</p>

app/views/coggins/edit.html.erb
<br>
<% if @coggin.errors.any? %>
  <div id="error_explanation-coggin">
    <h2><%= pluralize(@coggin.errors.count, "error") %> prohibited this coggin from being saved:</h2>
      <ul>
        <% @coggin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

<%= bootstrap_form_for(@coggin) do |f| %>
  <div class="container">
        <h1>Edit Coggins File</h1>
          <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
          <%= f.file_field :coggin %>
        <div>
          <%= f.submit 'Update', class: "btn btn-success" %>
            <%= link_to "Delete Coggins", coggin_path(@coggin.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
            <%= link_to "Back", :back, class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/coggins/index.html.erb
<br />
<div class="text-center">
<%= link_to "Add New Coggins Report", new_coggin_path %>
<!-- class: "btn btn-lg btn-primary text-center" %> -->
</div>
<br />
<br />

<table class = "table table-dark table-striped table-hover text-center">
   <thead>
      <tr>
         <th>Horse ID:</th>
         <th>Horse Name: </th>
         <th>Download Link: </th>
         <th>Delete Record?</th>
      </tr>
   </thead>
   <tbody>
      <% @coggins.each do |coggin| %>
         <tr>
            <td># <%= coggin.horse_id %> </td>
            <td><%= coggin.horse.try(:barn_name) %></td>
            <td><%= link_to "Download Coggins Report", coggin.coggin_url, class: "btn btn-outline-primary" %> </td>
            <td><%= button_to "Delete",  coggin, method: :delete, class: "btn btn-outline-danger", confirm: "Are you sure that you wish to delete #{coggin.id}?" %></td>
         </tr>

      <% end %>
   </tbody>

</table>

app/views/coggins/new.html.erb
<br>
<% if @coggin.errors.any? %>
  <div id="error_explanation-coggin">
    <h2><%= pluralize(@coggin.errors.count, "error") %> prohibited this coggin from being saved:</h2>
      <ul>
      <% @coggin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  </div>
<% end %>
  
<div class='container'>
  <%= bootstrap_form_for(@coggin) do |f| %>
    <%= f.select :horse_id, Horse.all.collect { |h| [h.barn_name, h.id] } %>
    <%= f.file_field :coggin %>
    <br />
    <%= f.submit "Submit", class: 'btn btn-success' %> <%= link_to "Back", user_path(@current_user), class:'btn btn-outline-secondary' %>
    <br />
    <br />
    <%= link_to "Home", user_path(@current_user), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/coggins/show.html.erb
<br>
  <div class='container'>
    <div class="row">
      <div class="small-6 large-centered columns">
        <div id='coggin_info'>
          <h1> Coggins File For: <%= @coggin.horse.barn_name%><h1>
          <div id='coggin_data'>
            <h3>Coggins File ID: <%= @coggin.id %></h3>
            <% if current_user.admin? %>
              <%= link_to "Download Coggins File", @coggin.coggin_url, download: '', class: "btn btn-outline-primary" %>
              <%= link_to 'Edit Coggins', edit_coggin_path(params[:id]), class: "btn btn-outline-info" %>
              <%= link_to 'Back to Horse', horse_path(@coggin.horse_id), class: "btn btn-outline-secondary" %>
              <% else %>
              <%= link_to "Download Coggins File", @coggin.coggin_url, download: '', class: "btn btn-outline-primary" %>
              <%= link_to 'Back to Horse', horse_path(@coggin.horse_id), class: "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>