config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users
    resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events
    resources :problems
    resources :notes, only: [:index, :show]
    resources :coggins, only: [:index, :show]
    resources :issues, only: [:show]
    resources :medications, only: [:index, :show]
    resources :plans do
      resources :subscriptions
    end
    mount StripeEvent::Engine, at: '/stripe_events'
  end

  resources :horses do
    resources :users, only: [:show]
    resources :events
    resources :problems, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
    resources :coggins, except: [:index, :show]
    resources :issues
    resources :medications

  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :events
  resources :problems
  resources :coggins
  resources :issues
  resources :medications
  resources :charges


  get '/horses/:user_id', to: 'problems#problems'
  root 'users#new'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

end







# Define abilities for the passed in user here. For example:
    #

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def admin?
    role == "admin"
  end

  def manager?
    role == "manager"
  end

  def employee?
    role == "employee"
  end

  def boarder?
    role == "boarder"
  end 
  
end

app/models/charge.rb
class Charge < ApplicationRecord
    has_and_belongs_to_many :horses
    belongs_to :user
end

app/models/coggin.rb
class Coggin < ApplicationRecord
  belongs_to :horse
  
  mount_uploader :coggin, CogginUploader # Tells rails to use this uploader for this model.
  validates :coggin, presence: true

  end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/farrier.rb
class Farrier < ApplicationRecord
  has_many :horses

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true
  
end

app/models/horse.rb
class Horse < ApplicationRecord

  belongs_to :user
  belongs_to :veterinarian
  belongs_to :farrier
  has_many :problems
  has_many :medications
  has_many :notes
  has_many :coggins

  mount_uploader :picture, PictureUploader

  validates :barn_name, presence: true
  validates :breed, presence: true
  validates :user_id, presence: true
  validates :veterinarian_id, presence: true
  validates :farrier_id, presence: true
end

app/models/medication.rb
class Medication < ApplicationRecord
    belongs_to :horse
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :horse
  
  validates :text,
  presence: true,
  length: { minimum: 10, maximum: 2000 }

end

app/models/problem.rb
class Problem < ApplicationRecord

    belongs_to :horse

    validates :horse, presence: true
    validates :date, presence: true
    validates :description, presence: true
    validates :time, presence: true









  end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :confirmable

  has_many :horses
  has_many :charges
  has_many :problems
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true

end

app/models/veterinarian.rb
class Veterinarian < ApplicationRecord
  has_many :horses

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :authorize_user
  after_action :verify_authorized


  def show
      @horse = Horse.find(params[:id])
      @veterinarian = @horse.veterinarian
      @farriers = @horse.farrier
      @charges = Charge.all
      @events = Event.all
      @notes = Note.all
      @problems = Problem.all
      @user = User.all
      authorize @horse
  end

  def new
    @horse = Horse.new
    authorize @horse
  end

  def create
    @horse = Horse.new(horse_params)
    authorize @horse
    if @horse.save
      flash[:notice] = "New Horse Added!"
      redirect_to @horse
    else
      flash[:alert] = "Error: Horse Not Created"
      render :new
    end
  end

  def edit
    @horse = Horse.find(params[:id])
    authorize @horse
  end

  def update
   @horse = Horse.find(params[:id])
   authorize @horse
   if @horse.update_attributes(horse_params)
     flash[:notice] = "Horse Updated!"
     redirect_to @horse
   else
      flash[:alert] = "Error: Horse Not Updated!"
     render 'edit'
   end
 end

  def destroy
    @horse = Horse.find(params[:id])
    authorize @horse
    if @horse.destroy
      flash[:notice] = 'Horse has been deleted.'
      redirect_to new_horse_path
    end
  end

  private

  def horse_params
    params.require(:horse).permit(
      :registered_name,
      :user_id,
      :id,
      :barn_name,
      :discipline,
      :breed,
      :picture,
      :veterinarian_id,
      :farrier_id,
      :problem,
      :name
    ).to_h
  end

  def authorize_user
    if !user_signed_in?
      redirect_to root_url
    end
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authorize_user, except: [:show]
  after_action :verify_authorized


  def show
    @note = Note.find(params[:id])
    @horse = @note.horse
    authorize @note
  end

  def new
    @note = Note.new
    authorize @note

  end

  def create
    @note = Note.new(note_params)
    authorize @note
    if @note.save
      flash[:notice] = "New Note Added!"
      redirect_to @note
    else
      flash[:alert] = "New Note Not Created"
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
    authorize @note
  end

  def update
   @note = Note.find(params[:id])
   authorize @note
   if @note.update_attributes(note_params)
     flash[:notice] = "Note Updated!"
     redirect_to @note
   else
     render :edit
   end
 end

  def destroy
    @note = Note.find(params[:id])
    authorize @note
    if @note.destroy
      flash[:notice] = 'Note has been deleted.'
      redirect_to new_note_path
    end
  end

  private

  def note_params
    params.require(:note).permit(
      :text,
      :horse_id
    )
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coggins_helper.rb
module CogginsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/horses/edit.html.erb
<div class='wrapper'>
<%= simple_form_for @horse do |f| %>
<% if @horse.errors.any? %>
<div id="error_explanation-horse">
        <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>
        <ul>
        <% @horse.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

<div class='container'>
  <%= bootstrap_form_for(@horse) do |f| %>
    <%= f.text_field :registered_name, required: true %>
    <%= f.text_field :barn_name, required: true %>
    <%= f.text_field :breed, required: true %>
    <%= f.text_field :discipline %>
    <%= f.select :user_id, User.all.collect { |o| [o.name, o.id] }, {label: 'Horse Owner'}  %>
    <%= f.select :veterinarian_id, Veterinarian.all.collect { |v| [v.name, v.id] } %>
    <%= f.select :farrier_id, Farrier.all.collect { |f| [f.name, f.id] } %>
    <%= f.file_field :picture, label: 'Choose Picture' %>
    <%= f.file_field :coggin, label: "Update Coggins" %>
    <%= f.submit "Update", class: 'btn btn-success' %> <%= link_to "Back", :back, class: 'btn btn-outline-secondary' %>
    <br />
    <br />
    <%= link_to "Home", user_path(), class: 'btn btn-sm btn-primary' %>
  <% end %>
</div>

app/views/horses/index.hmtl.erb
<% @charges.each do |c| %>
            <% if c.user_id === @horse.user_id %>
              <a href= <%= charge_path(c.id) %>>
              <p><%= c.created_at.strftime("%b. %d, %Y") %>: <%= c.description %>: $<%= c.amount %></p>
              </a>
              <% else %>
                <% end %>
              <% end %>

app/views/horses/new.html.erb
<div class='wrapper'>
<%= simple_form_for @horse do |f| %>
<% if @horse.errors.any? %>
<div id="error_explanation-horse">
        <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>
        <ul>
        <% @horse.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

<div class='container'>
  <%= bootstrap_form_for(@horse) do |f| %>
    <%= f.text_area :registered_name, required: true %>
    <%= f.text_area :barn_name, required: true %>
    <%= f.text_area :breed, required: true %>
    <%= f.text_area :discipline %>
    <%= f.select :user_id, User.all.collect { |p| [p.name, p.id] }, {label: 'Horse Owner'}  %>
    <%= f.select :veterinarian_id, Veterinarian.all.collect { |v| [v.name, v.id] } %>
    <%= f.select :farrier_id, Farrier.all.collect { |f| [f.name, f.id] } %>
    <%= f.file_field :picture, label: 'Choose Picture', required: true %>
    <%= f.submit "Submit", class: 'btn btn-success' %> <%= link_to "Back", :back, class: 'btn btn-outline-secondary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/horses/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      <div class="card " style="width: 20rem;">
        <h4 class="card-header text-center"><%= @horse.barn_name %> </h4>
        <%= image_tag @horse.picture.url, :class => "card-img-top" %>
          <div class="card-body text-center">
            <h5> Owner: <%= @horse.user.name %></h5>
            <p> Owner's Email: <%= mail_to @horse.user.email %></p>
            <p>Owner's Phone Number:<br /><%= number_to_phone(@horse.user.phone_number) %></p>
            <p class="card-text"><p>Breed: <%= @horse.breed %>
            <br />                  Discipline: <%= @horse.discipline %></p>                       
            <br />
            <h4 class="card-header lead">Registered Name:
            <br /><%= @horse.registered_name %></h4>
          </div>
          <div class="btn-group" role="group" aria-label="Basic example">
            <% if current_user.admin? || current_user.manager?  %>
            <%= link_to 'Update Horse', edit_horse_path(params[:id]), class: "btn btn-primary" %>
            <% end %>
            <%= link_to 'View Farrier', farrier_path(@horse.farrier_id), class: "btn btn-info" %>
            <%= link_to 'View Vet', veterinarian_path(@horse.veterinarian.id), class: "btn btn-secondary"%>
          </div>
      </div>    
    </div>
    <div class="col">
      <div class="list-group" id="myList" role="tablist">
        <a class="list-group-item list-group-item-action"  data-toggle="list" href="#problems-tab" role="tab" >View Problems</a>
        <a class="list-group-item list-group-item-action" data-toggle="list" href="#notes-tab" role="tab" >View Notes</a>
      </div>
    </div>
    <div class="col">
      <div class="anyList">
        <div class="tab-content" >
          <div class="tab-pane fade active" id="charges-tab" role="tabpanel"></div>
            <div class="tab-pane fade active" id="problems-tab" role="tabpanel">
              <% @problems.each do |p| %>
              <% if p.horse.id === @horse.id %>
              <a href= <%= problem_path(p.id) %>>
              <p><%= p.date.strftime("%b. %d, %Y") %>: <%= p.description %>: <%= p.notes %></p>
              <% end %>
              <% end %>
            </div></a>
            <div class="tab-pane fade" id="notes-tab" role="tabpanel">
              <% @notes.each do |n| %>
              <% if n.horse.id === @horse.id %>
              <a href= <%= note_path(n.id) %>>
              <p><%= n.created_at.strftime("%b. %d, %Y") %>: <%= n.text %></p>
              <% end %>
              <% end %>
              </a>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>