config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users
    resources :users, except: [:destroy] do
    resources :horses
    resources :charges, only: [:index, :show]
    resources :events
    resources :problems
    resources :notes, only: [:index, :show]
    resources :coggins, only: [:index, :show]
    resources :issues, only: [:show]
    resources :medications, only: [:index, :show]
    resources :plans do
      resources :subscriptions
    end
    mount StripeEvent::Engine, at: '/stripe_events'
  end

  resources :horses do
    resources :users, only: [:show]
    resources :events
    resources :problems, except: [:index, :show]
    resources :veternarians, only: [:show]
    resources :farriers, only: [:show]
    resources :notes, only: [:index, :show]
    resources :coggins, except: [:index, :show]
    resources :issues
    resources :medications

  end

  resources :farriers
  resources :veterinarians
  resources :notes
  resources :events
  resources :problems
  resources :coggins
  resources :issues
  resources :medications
  resources :charges


  get '/horses/:user_id', to: 'problems#problems'
  root 'users#new'
end

app/models/charge.rb
class Charge < ApplicationRecord
    has_and_belongs_to_many :horses
    belongs_to :user
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user


  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.fetch(:charge,
        :description,
        :amount,
        :stripe_email,
        :stripe_id
        )
    end
end

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>


<% if current_user.user.admin? || user.manager? %>
        <%= link_to 'Edit', edit_charge_path(params[:id]) %> <br />
     <% else %>
        <% if current_user.boarder? %>
            <%= link_to 'Show', @charge %> |
            <%= link_to 'Back', current_user %>
        <% end %>
        <% end %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Charges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<br />
<div class="container">
    <div class="row">
        <div class="col-8">
            <p> Hello,</p> 
            <p> The charge for <em><%= @charge.description %></em> in the amount of <mark>$<%= @charge.amount%></mark>
            was created on: <b><%= @charge.created_at.strftime("%b. %d, %Y,  %I:%M %p ") %></b></p>
            <p>If you would like to settle this charge now, you can do so by clicking the pay now button!</p>
                <br />
            <p> The last update to this charge was on:
            <b><%= @charge.updated_at.strftime("%b. %d, %Y, %I:%M %p") %></b></p>
                <br />
            <p class="btn btn-primary">Pay Now</p>

        </div>
    </div>
    <br />
    <% if current_user.admin? %>
        <%= link_to 'Edit', edit_charge_path(params[:id]) %> <br />
        <%= link_to 'Back to Horse', horse_path(@charge.horse_id) %>
     <% else %>
        <% if current_user.boarder? %>
            <%= link_to 'Back', current_user %>
        <% end %>
        <% end %>
</div>